config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'

 get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
   member do 
       get :followings
       get :followers
    end  
   end

  resources :schedules, only: [:index, :new, :show, :create, :destroy ]
  resources :relationships, only: [:new, :show, :create, :destroy]
end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :place, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 500 }
  validate :schedule_cannot_be_in_the_future
  
def schedule_cannot_be_in_the_future
  if schedule.present? && schedule > Date.today
    errors.add(:schedule, "can not specify your future date as your schedule date.")
  end
end


  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :schedules
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
    has_many :followers, through: :reverses_of_relationship, source: :user
    
    def follow(other_user)
     unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
     end
    end

    def unfollow(other_user)
     relationship = self.relationships.find_by(follow_id: other_user.id)
     relationship.destroy if relationship
    end

    def following?(other_user)
     self.followings.include?(other_user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
   
   include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_schedules = user.schedules.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
  end  
end 

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザーをフォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザーのフォローを解除しました'
    redirect_to user
  end  
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

    def index
        @schedules = Schedule.where(publicflag: 1)
    end
    
    def new
        @sched = current_user.schedules.build
        @schedules = current_user.schedules
    end
    
    
    def create
      #@sched = Schedules.new(schedule_params)
      @sched =  current_user.schedules.build(schedule_params)
      if @sched.save
          flash[:success] = 'スケジュールが正常に投稿されました'
          redirect_to @sched
      else
          flash.now[:danger] = 'スケジュールが投稿されませんでした'
          render :new
      end    
    end  

    
    def destroy 
        @sched = Schedule.find(params[:id])
        @sched.destroy
        flash[:success] ='スケジュールを削除しました'
        redirect_back(fallback_location: root_path)
    end
    
    def show
        @schedule = Schedule.find(params[:id])
    end
    
    private
    def schedule_params
         params.require(:schedule).permit(:start, :kind, :place, :publicflag, :content, :capacity, :deadline)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  def update
  end

  def edit
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show,:edit,:update]
  before_action :correct_user, only:[:edit, :update, :destroy]

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @schedules = @user.schedules.order('created_at DESC')#.page(params[:page])
    
    @secret = Schedule.where("start > '#{DateTime.now.in_time_zone('UTC')}'").where(user_id: current_user.following_ids, publicflag:0).order("deadline ASC")#.page(params[:page])

    @schedules = @schedules + @secret
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end  
    
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = '正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] ='更新されませんでした'
      render :edit
    end  
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to current_user
    end
  end 
end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">スケット</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
           <li><%= link_to 'ユーザー一覧', users_path %></li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                スケジュール
                <span class="caret"></span>
              </a>
              
             <ul class="dropdown-menu">
                <li><%= link_to "スケジュール一覧", schedules_path %></li>
              
             </ul>
          </li>
          
          <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                <li><%= link_to 'マイプロフィール', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to '新規スケジュール', new_schedule_path %></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </ul>
              </li>
          <% else %>
         <li><%= link_to '会員登録', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
       </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Suketto</title>
    <%= csrf_meta_tags %>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
     <div class="container">
      <%= render 'layouts/flash_messages' %>
    <%= yield %>
     </div>
  </body>
</html>

app/views/layouts/error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/schedules/_schedules.html.erb
<ul class="media-list">
  <% schedules.each do |schedule| %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(schedule.user, options = { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to schedule.user.name, user_path(schedule.user) %> <span class="text-muted">posted at <%= schedule.created_at %></span>
        </div>
        <div>
          <p><%= schedule.content %></p>
        </div>
        <div>
          <% if current_user == schedule.user %>
            <%= link_to "Delete", root_path, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%#= paginate schedules %>
</ul>

app/views/schedules/create.html.erb
<h1>Schedules#create</h1>
<p>Find me in app/views/schedules/create.html.erb</p>

app/views/schedules/destroy.html.erb
<h1>Schedules#destroy</h1>
<p>Find me in app/views/schedules/destroy.html.erb</p>

app/views/schedules/edit.html.erb
<h1>Schedules#edit</h1>
<p>Find me in app/views/schedules/edit.html.erb</p>

app/views/schedules/index.html.erb
<div class="row">

  <div class="col-md-6 col-md-offset-3">
      <h1>全体公開された スケジュール</h1>
      <%= month_calendar(attribute: :start,  events: @schedules) do |date, schedules| %>
          <%= date %>
          <% schedules.each do |schedule| %>
            <div>
               <%= link_to schedule.content, schedule_path(schedule) %>
            </div>
          <% end %>
        <% end %>
    </div>
</div>

app/views/schedules/new.html.erb
<div class="text-center">
  <h1>スケジュール登録完了</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@sched) do |f| %>
    
      
         <%= render 'layouts/error_messages', model: f.object %>
      
        <div class="form-group">
          <%= f.label :start, "開始", class:"control-label" %>
          <%= f.datetime_select :start, class:"form-control" %>
        </div>
         <%# 飲み会,ご飯・お茶,趣味,イベント・パーティー,勉強会,特になし,その他 %>
        <%= f.select :kind, {"飲み会" => "飲み会", 
                            "ご飯・お茶" => "ご飯・お茶",
                            "趣味" => "趣味",
                            "イベント・パーティー" => "イベント・パーティー",
                            "勉強会" => "勉強会",
                            "特になし" => "特になし",
                            "その他" => "その他" }, class:"form-control" %>
                            <br>
        <%= f.label :place, "場所", class:"control-label" %>
        <%= f.text_field :place, class:"form-control" %>
        <%= f.select :publicflag, {"非公開" => 0, "公開" => 1 }, class:"form-control" %>
        <br>
        <%= f.label :content, "詳細", class:"control-label" %>
        <%= f.text_area :content, class:"form-control" %>
        <%= f.label :capacity, "人数", class:"control-label" %>
        <%= f.number_field :capacity, class:"form-control" %>

        <div class="form-group">

          <%= f.label :deadline, "締切", class:"control-label" %>
          <%= f.datetime_select :deadline, class:"form-control" %>
        </div>        
        <%= f.submit "登録", class:"btn btn-danger" %>
    
    <% end %>
    
  </div>
</div>

app/views/schedules/show.html.erb
<div class="text-center">
  <h1>New Schedule</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">



        <table class="table">
            <tr>
                
                <td>開始</td>
                <td><%= @schedule.start.strftime("%Y/%m/%d") %></td>
            </tr>
            <tr>
                <td>種別</td>
                <td><%= @schedule.kind %></td>
            </tr>   
            <tr>
                <td>場所</td>
                <td><%= @schedule.place %></td>
            </tr>
            
             <tr>
                <td>公開設定</td>
                <% if @schedule.publicflag == 1 %>
                    <td>公開</td>
                <% else %>
                    <td>非公開</td>
                <% end %>
            </tr>
            
            <tr>
                <td>詳細</td>
                <td><%= @schedule.content %></td>
            </tr>
            <tr>
                <td>人数</td>
                <td><%= @schedule.capacity %></td>
            </tr>
            <tr>
                <td>締切</td>
                <td><%= @schedule.deadline %></td>
            </tr>
         <%# 飲み会,ご飯・お茶,趣味,イベント・パーティー,勉強会,特になし,その他 %>
        
        
 
            </table>

  </div>
</div>

app/views/schedules/update.html.erb
<h1>Schedules#update</h1>
<p>Find me in app/views/schedules/update.html.erb</p>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/toppages/index.html.erb
<div class="center jumbotron">

　<% unless logged_in? %>
    <div class="text-center">
      <h1>スケット</h1><p>スケジュールからつながるトモダチづくり</p>
      <%= link_to '会員登録', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  <% else %>
    <h2>説明</h2>
    <p>新規スケジュール：スケジュール登録ができます。</p>
    <p>スケジュール一覧：公開されているスケジュールをチェックすることができます。</p>
    <p>ユーザー一覧：ほかのユーザーを見ることができます。気になるユーザーはフォローしてみましょう。</p> 
  <% end %>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'プロフィール', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>マイプロフィール</h1>
<p><%= @user.name %>さんのプロフィールの変更画面</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Profile change', class: 'btn btn-primary btn-block' %>
      
      
    <% end %>
   </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Schedules <span class="badge"><%= @count_schedules %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Schedules <span class="badge"><%= @count_schedules %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>会員登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
      
      
    <% end %>
   </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
    
    <% if @user == current_user %>
       <%= link_to "プロフィールの変更", edit_user_path(@user), class:"btn btn-success" %>
    <% end %>
  </aside>
  <div class="col-xs-8">
<h1>プロフィール</h1>

    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Schedule <span class="badge"><%= @count_schedules %></span><% end %></li>
     
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
      <%= render 'schedules/schedules', schedules: @schedules %>
      <h2>スケジュール</h2>
      <%= month_calendar(attribute: :start,  events: @schedules) do |date, schedules| %>
        <%= date %>

        <% schedules.each do |schedule| %>
        
            <% if schedule.user == current_user %>
                <%= link_to schedule.content, schedule_path(schedule), class:"btn btn-xs btn-danger" %>
            <% else %>
                <%= link_to schedule.content, schedule_path(schedule), class:"btn btn-xs btn-primary" %>
            <% end %>
          <% end %>
        <% end %>
      
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>